---
# cSpell Settings

version: "0.2"

# flagWords - list of words to be always considered incorrect
# This is useful for offensive words and common spelling errors.
# For example "hte" should be "the"
flagWords:
  - hte

language: en

# words - list of words to be always considered correct: an Allowlist per-se
words:
  # Synology Architecture name
  - Denverton
  # bazel words
  - Stardoc
  - bazel
  - bazelisk
  - bazelrc
  - bazelspk
  - buildifier
  - bzlmod
  - ibazel
  # Vanity
  - allanc
  - chickenandpork
  - floppydog
  - looooong
  # Other entity proper names
  - FireHydrant
  - ThirdParty
  - RobertRoss
  # Actual useful words
  - BUILDNUM
  - buildable
  - configfile
  - crossbuild
  - crosstool
  - dockcross
  - helloworld
  - kernelmod
  - maint
  - mkdocs
  - netfilter
  - noarch
  - proto
  - softlink
  - softlinks
  - subdir
  - subdirs
