load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive", "http_file")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

# When reusing for your own project, consider using:
# git_repository(
#     name = "rules_synology",
#     commit = "9e79430c176e94ad6f4e2f5ef38cb30697d3b7ca",
#     remote = "https://github.com/chickenandpork/rules_synology.git",
# )

local_repository(
    name = "rules_synology",
    path = "../..",
)

load("@rules_synology//:deps.bzl", synology_deps = "deps")

synology_deps()
