name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions: write-all
      ## actions: read|write|none
      ##checks: write
      #contents: write
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "!wip"
          MERGE_METHOD_LABELS: "automerge=merge,autosquash=squash"
          MERGE_METHOD_LABEL_REQUIRED: true
          MERGE_COMMIT_MESSAGE: "pull-request-description"
          MERGE_RETRIES: "10"
          MERGE_RETRY_SLEEP: "30000"
          MERGE_REQUIRED_APPROVALS: "0"
          UPDATE_LABELS: ""
          UPDATE_METHOD: "rebase"
