name: Bazel build

env:
  HOMEBREW_NO_AUTO_UPDATE: 1
  # typically used for bazel internal testing: changes outputRoot, sets idletimeout to ~15s
  TEST_TMPDIR: /tmp/bazel

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - reopened
  push:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        # action runners have bazelisk: - uses: bazelbuild/setup-bazelisk@v2
        # https://github.com/bazelbuild/bazel/issues/11062
      - run: mkdir -p "${TEST_TMPDIR}"
      - run: env | sort
      - name: Mount bazel cache  # Optional
        uses: actions/cache@v3
        with:
          # needs to be an absolute path, not a variable; I've made it match TEST_TMPDIR above
          path: /tmp/bazel
          key: _bazel_runner
      - run: bazel build //...
      - run: bazel test //...
      - name: Build examples to ensure functionality
        run: |
            for d in $(find examples -name WORKSPACE -exec dirname {} \; ); do
            echo "::group::example: ${d}"
            (cd ${d} && bazel build //...);
            echo "::endgroup::"
            done
      - name: Test examples to ensure functionality
        # runs `bazel test` when subdirs have a "tests" subdir, assuming it includes unittests
        run: |
            for d in $(find examples -name tests -exec dirname {} \; ); do
            echo "::group::test example: ${d}"
            (cd ${d} && bazel test //...);
            echo "::endgroup::"
            done
  merge:
    runs-on: ubuntu-latest
    permissions:  # let's trim these after it's working
      # actions: read|write|none
      checks: write
      contents: write
      deployments: write
      discussions: write
      id-token: write
      issues: write
      packages: write
      pages: write
      pull-requests: write
      repository-projects: write
      # security-events: read|write|none
      statuses: write
    steps:
      - name: Merge Workflow for tagged PRs
        uses: squalrus/merge-bot@v0.4.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          blocking_labels: do not merge, invalid
          # reviewers: true  -- don't actually need a review, just a tag
          labels: automerge
          method: squash
          # "By default the pull request will be blocked by incomplete/failing checks."
          checks_enabled: true
          #
          # coupled with a change in config: https://github.com/chickenandpork/rules_synology/settings,
          # "Pull Requests" section, "[x] Automatically delete head branches"
          delete_source_branch: false
          reviewers: false
          test: true

