name: Bazel build

env:
  HOMEBREW_NO_AUTO_UPDATE: 1
  # typically used for bazel internal testing: changes outputRoot, sets idletimeout to ~15s
  TEST_TMPDIR: /tmp/bazel

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - reopened
  push:

jobs:
  doc:
    name: Docs on ubuntu-latest
    concurrency:
       # trivial group in this shallow matrix but autocatches expansion
       cancel-in-progress: true
       group: ${{ github.ref }}-${{ github.workflow }}-doc
    runs-on: ubuntu-latest
    steps:
      #-
      #  name: Date-Based Cache key
      #  # get a key showing the current week (ISO: yyyyWww) allowing older caches to age-out/autoprune
      #  id: week
      #  run: echo "::set-output name=iso::$(date +'bazel-%YW%U')"
      #-
      #  uses: bazel-contrib/setup-bazel@0.8.5
      #  with:
      #    # Cache bazel downloads via bazelisk
      #    bazelisk-cache: true
      #    # Store build cache per week
      #    disk-cache: ${{ steps.week.outputs.iso }}
      #    # Share repository cache between workflows.
      #    repository-cache: true
      - uses: actions/checkout@v4.2.2
        # https://github.com/bazelbuild/bazel/issues/11062
      -
        name: Documentation
        run: |
          echo 'examples' > .bazelignore  # remove '//docs'
          bazel run //docs:collate_docs

  build:
    name: Build on ${{ matrix.os }}
    concurrency:
       # trivial group in this shallow matrix but autocatches expansion
       cancel-in-progress: true
       group: ${{ github.ref }}-${{ github.workflow }}-${{ matrix.os }}-build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4.2.2
        # https://github.com/bazelbuild/bazel/issues/11062
      -
        name: Basic Build
        run: |
          echo 'docs' > .bazelignore
          echo 'examples' >> .bazelignore
          bazel build //...
      -
        name: Basic Test
        run: bazel test //... --test_output=errors --test_summary=detailed
      -
        name: Integration Tests (ie Proof Examples)
        run: |
          echo 'docs' > .bazelignore
          bazel test //examples:all_integration_tests --test_output=errors --test_summary=detailed
      -
        run: bazel shutdown
