name: Confirm Migrations

env:
  HOMEBREW_NO_AUTO_UPDATE: 1
  # typically used for bazel internal testing: changes outputRoot, sets idletimeout to ~15s
  TEST_TMPDIR: /tmp/bazel

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - reopened
  push:

jobs:
  build:
    name: Confirm Zero Outstanding Migrations
    concurrency:
       # trivial group in this shallow matrix but autocatches expansion
       cancel-in-progress: true
       group: ${{ github.ref }}-${{ github.workflow }}-${{ matrix.os }}-build
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v5.0.0
        # https://github.com/bazelbuild/bazel/issues/11062
      -
        run: bazelisk --migration build //...
      # If migrations ultimately pass due to dependencies updating, I'll be able to merge this
