name: Publish docs via GitHub Pages

env:
  HOMEBREW_NO_AUTO_UPDATE: 1
  # typically used for bazel internal testing: changes outputRoot, sets idletimeout to ~15s
  TEST_TMPDIR: /tmp/bazel

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4.2.0
        # action runners have bazelisk: - uses: bazelbuild/setup-bazelisk@v2
        # https://github.com/bazelbuild/bazel/issues/11062
      -
        run: mkdir -p "${TEST_TMPDIR}"
      -
        name: Mount bazel cache  # Optional
        uses: actions/cache@v4
        with:
          # needs to be an absolute path, not a variable; I've made it match TEST_TMPDIR above
          path: /tmp/bazel
          key: _bazel_runner
      -
        name: Collate Docs
        run: bazel run //docs:collate_docs
      -
        name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.26
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml
          EXTRA_PACKAGES: build-base
          # see https://github.com/marketplace/actions/deploy-mkdocs#example-usage
          # REQUIREMENTS: folder/requirements.txt
